#!/usr/bin/env python3
"""
dnsmasq-ui: Web UI for managing dnsmasq DNS records across multiple servers.
"""

from flask import Flask, render_template, request, jsonify, redirect, url_for
from flask_cors import CORS
import json
import os
import subprocess
from pathlib import Path
from datetime import datetime
import paramiko
from functools import wraps

app = Flask(__name__)
CORS(app)

# Configuration
CONFIG_FILE = os.getenv('DNSMASQ_UI_CONFIG', '/etc/dnsmasq-ui/servers.json')
RECORDS_FILE = os.getenv('DNSMASQ_RECORDS_FILE', '/etc/dnsmasq.d/local-records.conf')
SSH_KEY = os.getenv('SSH_KEY', os.path.expanduser('~/.ssh/id_rsa'))
SSH_USER = os.getenv('SSH_USER', 'debian')

# Default servers if config doesn't exist
DEFAULT_SERVERS = {
    'dns01': {'ip': '192.168.0.231', 'hostname': 'dns01', 'status': 'unknown'},
    'dns02': {'ip': '192.168.0.232', 'hostname': 'dns02', 'status': 'unknown'},
    'dns03': {'ip': '192.168.0.233', 'hostname': 'dns03', 'status': 'unknown'},
}

class DNSRecord:
    """Represents a DNS record (A, AAAA, CNAME)."""
    def __init__(self, domain, record_type, value):
        self.domain = domain
        self.record_type = record_type
        self.value = value

    def to_dnsmasq(self):
        """Convert to dnsmasq format."""
        if self.record_type == 'CNAME':
            return f"cname={self.domain},{self.value}"
        else:
            return f"address=/{self.domain}/{self.value}"

    def to_dict(self):
        return {
            'domain': self.domain,
            'type': self.record_type,
            'value': self.value
        }

    @staticmethod
    def from_dnsmasq(line):
        """Parse dnsmasq format line."""
        line = line.strip()
        if not line or line.startswith('#'):
            return None

        if line.startswith('cname='):
            parts = line.replace('cname=', '').split(',')
            if len(parts) == 2:
                return DNSRecord(parts[0], 'CNAME', parts[1])
        elif line.startswith('address=/'):
            parts = line.replace('address=/', '').split('/')
            if len(parts) == 2:
                record_type = 'AAAA' if ':' in parts[1] else 'A'
                return DNSRecord(parts[0], record_type, parts[1])

        return None

class DNSManager:
    """Manages DNS records across multiple dnsmasq servers."""

    def __init__(self, servers_config):
        self.servers = servers_config

    def ssh_command(self, server_ip, command):
        """Execute command on remote server via SSH."""
        try:
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(server_ip, username=SSH_USER, key_filename=SSH_KEY, timeout=5)
            stdin, stdout, stderr = ssh.exec_command(command)
            output = stdout.read().decode()
            error = stderr.read().decode()
            ssh.close()
            return output, error, True
        except Exception as e:
            return '', str(e), False

    def get_records(self, server_ip):
        """Fetch DNS records from a server."""
        cmd = f"cat {RECORDS_FILE}"
        output, error, success = self.ssh_command(server_ip, cmd)

        records = []
        if success:
            for line in output.split('\n'):
                record = DNSRecord.from_dnsmasq(line)
                if record:
                    records.append(record)

        return records, success

    def update_records(self, server_ip, records):
        """Update DNS records on a server."""
        content = "# Local DNS Records for ad.alshowto.com\n"
        content += "# Auto-generated by dnsmasq-ui\n\n"

        for record in records:
            content += record.to_dnsmasq() + "\n"

        content += "\n# Upstream DNS\n"
        content += "server=1.1.1.1\n"
        content += "server=8.8.8.8\n"

        # Write to temp file, then move
        cmd = f"echo '{content.replace(chr(39), '\"')}' | sudo tee {RECORDS_FILE} > /dev/null && sudo systemctl restart dnsmasq"
        output, error, success = self.ssh_command(server_ip, cmd)

        return success, error if error else "Records updated successfully"

    def check_status(self, server_ip):
        """Check if dnsmasq is running on server."""
        cmd = "sudo systemctl is-active dnsmasq"
        output, error, success = self.ssh_command(server_ip, cmd)
        return success and 'active' in output.lower()

def load_servers():
    """Load servers configuration."""
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE) as f:
                return json.load(f)
        except:
            return DEFAULT_SERVERS
    return DEFAULT_SERVERS

def get_dns_manager():
    """Get DNSManager instance."""
    return DNSManager(load_servers())

# Routes
@app.route('/')
def index():
    """Dashboard showing all DNS servers."""
    manager = get_dns_manager()
    servers_status = []

    for name, config in manager.servers.items():
        status = 'online' if manager.check_status(config['ip']) else 'offline'
        servers_status.append({
            'name': name,
            'ip': config['ip'],
            'hostname': config['hostname'],
            'status': status
        })

    return render_template('dashboard.html', servers=servers_status)

@app.route('/server/<server_name>')
def server_detail(server_name):
    """Show DNS records for a specific server."""
    manager = get_dns_manager()

    if server_name not in manager.servers:
        return redirect(url_for('index'))

    server = manager.servers[server_name]
    records, success = manager.get_records(server['ip'])

    return render_template('server.html',
                         server_name=server_name,
                         server=server,
                         records=[r.to_dict() for r in records])

@app.route('/api/records/<server_name>', methods=['GET'])
def api_get_records(server_name):
    """API: Get DNS records from server."""
    manager = get_dns_manager()

    if server_name not in manager.servers:
        return jsonify({'error': 'Server not found'}), 404

    server = manager.servers[server_name]
    records, success = manager.get_records(server['ip'])

    if not success:
        return jsonify({'error': 'Failed to fetch records'}), 500

    return jsonify({
        'server': server_name,
        'records': [r.to_dict() for r in records]
    })

@app.route('/api/records/<server_name>', methods=['POST'])
def api_update_records(server_name):
    """API: Update DNS records on server."""
    manager = get_dns_manager()

    if server_name not in manager.servers:
        return jsonify({'error': 'Server not found'}), 404

    data = request.json
    records = []

    for record_data in data.get('records', []):
        records.append(DNSRecord(
            record_data['domain'],
            record_data['type'],
            record_data['value']
        ))

    server = manager.servers[server_name]
    success, message = manager.update_records(server['ip'], records)

    if not success:
        return jsonify({'error': message}), 500

    return jsonify({
        'message': message,
        'server': server_name,
        'updated_at': datetime.now().isoformat()
    })

@app.route('/api/status', methods=['GET'])
def api_status():
    """API: Check status of all servers."""
    manager = get_dns_manager()
    status = {}

    for name, config in manager.servers.items():
        is_online = manager.check_status(config['ip'])
        status[name] = {
            'ip': config['ip'],
            'online': is_online
        }

    return jsonify(status)

@app.errorhandler(404)
def not_found(error):
    return jsonify({'error': 'Not found'}), 404

@app.errorhandler(500)
def server_error(error):
    return jsonify({'error': 'Internal server error'}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=False)
