version: 2
ethernets:
  eth0:
    dhcp4: false
    match:
      macaddress: "bc:24:11:65:e1:01"
    addresses:
      - 192.168.0.253/24
    gateway4: 192.168.0.1
    nameservers:
      addresses:
        - 192.168.0.250
        - 1.1.1.1
        - 8.8.8.8
    optional: false
