[dns_servers]
dns01 ansible_host=192.168.0.231 ansible_user=debian ansible_become=yes
dns02 ansible_host=192.168.0.232 ansible_user=debian ansible_become=yes
dns03 ansible_host=192.168.0.233 ansible_user=debian ansible_become=yes

[dns_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa
