[dns_servers]
dns01 ansible_host=192.168.0.231 ansible_user=debian ansible_become=yes
dns02 ansible_host=192.168.0.232 ansible_user=debian ansible_become=yes
dns03 ansible_host=192.168.0.233 ansible_user=debian ansible_become=yes

[dns_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa

# Proxmox Infrastructure
[proxmox_nodes]
pve01 ansible_host=192.168.7.11 ansible_user=root ansible_ssh_pass=Hpy@7400adm proxmox_node=pve01
pve03 ansible_host=192.168.7.13 ansible_user=root ansible_ssh_pass=Hpy@7400adm proxmox_node=pve3
pve04 ansible_host=192.168.7.14 ansible_user=root ansible_ssh_pass=Hpy@7400adm proxmox_node=pve04
pve06 ansible_host=192.168.7.16 ansible_user=root ansible_ssh_pass=Hpy@7400adm proxmox_node=pve06

[proxmox_nodes:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
proxmox_cluster_name=pve

# All groups
[all:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=no
